### ISSUE TITLE
Desktop folder

### ISSUE THREAD

**Issue by dflock** [gerstner-hub/xwmfs#3]
This is amazing work - I love it! This should be built into X11/Linux - although a bit late for that probably :)

I'd really love a desktops folder, with the obvious structure:

```
desktops/
   - id/ desktop id folder, containing the following files
	   - id
	   - name
	   - windows/ : folder with symlinks to the window files that are on that desktop
```

Ideally some of this is writable to allow you to create/delete desktops and change their names, but read-only would be a great start.

I know this is unlikely to happen unless I write it, but putting this here anyway ;)

Thanks for your work on this project, really appreciated!

**Comment by gerstner-hub** [comment]
Great to hear that you like the project.

It has been a while that I touched the code and the X specifics can be quite horrible to get into again. But I will have a look these days how much effort it will be.

**Comment by gerstner-hub** [comment]
I just looked a bit more closely into your request. Actually it should not be all that hard to implement, given that all the information is already available and no new X11 APIs need to be accessed.

I don't think there is such a thing as a "desktop ID", however, desktops only seem to have names. So we would get

```
desktops -> name_of_desktop_1 -> {name, windows -> { window1 -> ../../../windows/window1, ... } }
```

I will dig a bit more into this and see how far I get into adding this feature.

**Comment by gerstner-hub** [comment]
Of course implementing this was quite a lot more work than what it looked like at first. However, I have a working implementation on the `desktop_folder` branch. I didn't test this extensively yet. Do you care to give it a try before I release the code on the master branch?

**Comment by gerstner-hub** [comment]
Looks like you're busy, so I've done some further rudimentary testing and I think it is safe to release this new state of the code.

**Comment by dflock** [comment]
Sorry for the late reply!

I've tested this, and it works great - thank you so much for putting in the time an effort to add this feature! Your hard work is much appreciated.
